Feature/add footer
MarianaSouza/web-dev-path pull request #43
Opened 2021-06-18 01:29 UTC by rebecatschiedel

|                        Web Dev Path                      |
| :-----------------------------------------------------------: |
| [**38**](https://github.com/MarianaSouza/web-dev-path/issues/38) |

#### What is this change?
A footer structure and style are being added to the project.

#### Were there any complications while making this change?
No.

#### How did you verify this change?
Locally.

#### When should this be merged?
After code review

2021-06-19 01:07 UTC, Schlickmann reviewed
Looking good, just left a couple of suggestions here 😃

2021-06-19 01:07 UTC, Schlickmann commented on components/Footer.js
> +            </li>
We could create a constant with the following structure in a utils file or something.

```
const links = [
   { text: 'About Us',  href: '/about-us' },
   { text: 'Blog',  href: '/blog' },
   { text: 'Contact Us',  href: '/contact-us' },
]
```

then here we could do the following to remove some repeated code.

```suggestion
{links.map((link) => (
  <li className={footerStyles.footerItem} key={link.href}>
    <Link href={link.href}>
      <a>{link.text}</a>
    </Link>
  </li>
))}
```

2021-06-19 01:07 UTC, Schlickmann commented on components/Footer.js
> +            </Link>
Same idea here for the social media links 😄

2021-06-19 18:43 UTC, MarianaSouza commented on components/Footer.js
> +            </li>
That's a great idea, Juliani and @rebecatschiedel ! If you feel comfortable about implementing this @rebecatschiedel , pls go ahead.

2021-06-19 18:47 UTC, MarianaSouza commented on components/Footer.js
> +            </Link>
Agreed, Juliani! In that same utils file @rebecatschiedel , you could create a `const linksSocial` and map through it after importing the utils file to the component as Juliani mentioned above.

2021-06-19 19:36 UTC, MarianaSouza requested changes
Overall the footer structure is great, @rebecatschiedel , thanks so much! Just a few minor changes ;)

2021-06-19 19:36 UTC, MarianaSouza commented on pages/index.js
> +    <div>
Is there any particular reason why you removed the container here, @rebecatschiedel ?

2021-06-19 19:36 UTC, MarianaSouza commented on styles/Footer.module.css
> +  height: 5em;
Could you pls change height for width: 4.5rem here to make the logo a little bit smaller?

2021-06-19 19:36 UTC, MarianaSouza commented on public/iconmonstr-twitter-4.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M12 0c-6.627 0-12 5.373-12 12s5.373 12 12 12 12-5.373 12-12-5.373-12-12-12zm6.066 9.645c.183 4.04-2.83 8.54
Inside the images folder, could you pls create an svg folder and place the svg files there after renaming them to iconmonstr-github.svg and iconmonstr-twitter.svg (without the numbers), pls?

Also, could you pls delete the logo file that is not in use?

2021-06-21 02:23 UTC, rebecatschiedel commented on pages/index.js
> +    <div>
Not really, I believe I changed after changing the styles but I was supposed to add it back. My mistake!!

2021-06-21 02:27 UTC, rebecatschiedel commented on components/Footer.js
> +            </li>
I am on it!!
Thank you @Schlickmann !! Sometimes I forgot I can use logic inside HTML and CSS. 
My navbars will never be the same anymore!! =)

2021-06-21 05:01 UTC, rebecatschiedel commented
Is the favicon working for anyone? It worked for me, at first, but now it is gone.

2021-06-22 03:46 UTC, MarianaSouza approved these changes
Way to go, @rebecatschiedel !

2021-06-22 04:44 UTC, merged