Chore/update home content
MarianaSouza/web-dev-path pull request #49
Opened 2021-07-14 05:21 UTC by manecipoglu

|                        Web Dev Path                      |
| :-----------------------------------------------------------: |
| [**45**](https://github.com/MarianaSouza/web-dev-path/issues/45) |

#### What is this change?
Update the home content with  two headers one button and 4 card elements with responsive styling. 

#### Were there any complications while making this change?
Chaging of a media break point from 600px to 728px.

#### How did you verify this change?
Locally.

#### When should this be merged?
After code review.

2021-07-17 23:28 UTC, MarianaSouza requested changes
There are just some details we could adapt to make this PR even better, @manecipoglu !

Please let me know if you have any questions:
https://www.loom.com/share/10c37afced934b9eaf6843d395c14964

2021-07-17 23:28 UTC, MarianaSouza commented on styles/Home.module.css
> +  /* max-width: 50rem; */
Pls remove the comment.

2021-07-17 23:38 UTC, MarianaSouza commented
Hey @ZahraB21 , I tagged you as a reviewer here too because of the video above I left for @manecipoglu . I think you could benefit from that info too <3

2021-07-26 04:45 UTC, MarianaSouza requested changes
We're almost there, @manecipoglu ! Thank you!

2021-07-26 04:45 UTC, MarianaSouza commented on styles/Home.module.css
> +  width: 25%;
Could you please change the width here to 8rem, @manecipoglu ?

2021-08-02 18:58 UTC, MarianaSouza approved these changes
Looks great! Thanks @manecipoglu  All yours to merge!

2021-08-03 16:01 UTC, Schlickmann commented on styles/Home.module.css
> +  background-color: #696969;
[not a blocker] Just leaving this suggestion here... can we start using variables to hold these values, like colours and padding and margin...

e.g. `margin-base; margin-2; padding-base; padding-2; $colour-gray` and so on...

2021-08-03 16:01 UTC, Schlickmann approved these changes

2021-08-04 02:55 UTC, MarianaSouza commented on styles/Home.module.css
> +  background-color: #696969;
I love this idea for the next task, @Schlickmann ! Would you like to write a detailed issue to address that?

2021-08-06 01:59 UTC, merged

2021-08-06 02:00 UTC, manecipoglu commented
I have been searching for the safe git commands to merge this for a while until I came to this page and see that I can do that with a single click of a button. GUI rocks :P

2021-08-06 03:50 UTC, MarianaSouza commented
> I have been searching for the safe git commands to merge this for a while until I came to this page and see that I can do that with a single click of a button. GUI rocks :P

Right? Another good practice @manecipoglu is deleting the branch after merging a PR, which helps to keep the repo clean. You just need to click the "Delete branch: button above :)

2021-08-06 04:09 UTC, manecipoglu commented
> > I have been searching for the safe git commands to merge this for a while until I came to this page and see that I can do that with a single click of a button. GUI rocks :P
> 
> Right? Another good practice @manecipoglu is deleting the branch after merging a PR, which helps to keep the repo clean. You just need to click the "Delete branch" button below :)

Magic :))