fixed oveflowing nav menu
MarianaSouza/web-dev-path pull request #53
Opened 2021-08-11 15:44 UTC by manikmmalhotra

|                        Web Dev Path                      |
| :-----------------------------------------------------------: |
| [**#51**](https://github.com/MarianaSouza/web-dev-path/issues/issueNumber) |

#### What is this change?
fixed overflow in mobile view when closing nav menu

2021-08-12 01:11 UTC, MarianaSouza requested changes
Good job on this first PR @manikmmalhotra ! :D

Could you please change adjust these points and request me a second review?

1. Please adjust your PR description by adding the issue number, which is 51 (without the #). That will create a valid link to the issue. Also, it's not the case since we could test the navbar on any page, but, when you have more complicated features, you need to describe at least how to test that feature.

![Screen Shot 2021-08-11 at 5 54 21 PM](https://user-images.githubusercontent.com/20016897/129122997-44ce30c6-52cd-4ae7-b4f3-9553050e9c92.png)
![Screen Shot 2021-08-11 at 5 53 28 PM](https://user-images.githubusercontent.com/20016897/129122999-508a20d1-44e1-4e6a-8c4a-b453dff3fcde.png)

2. Please assign yourself to the PR (it's like your kid now :) and you're the one responsible for it until it's merged and released ) and also link to the correspondent issue.
![Screen Shot 2021-08-11 at 5 55 21 PM](https://user-images.githubusercontent.com/20016897/129123092-e8097f8b-9a07-4316-8a20-8c6a796bc3e9.png)

Thank you!

2021-08-17 17:11 UTC, manecipoglu approved these changes
Looks solid. Thanks @manikmmalhotra Manik!

I am going to go ahead and approve but please merge your PR only after Mariana's approval.

2021-08-19 16:47 UTC, Schlickmann approved these changes

2021-09-05 00:01 UTC, MarianaSouza commented
This PR fix is being addressed by the #55

2021-09-05 00:01 UTC, closed without merging