Convert CSS to SASS
MarianaSouza/web-dev-path pull request #55
Opened 2021-08-18 18:18 UTC by ZahraB21

|                        Web Dev Path                      |
| :-----------------------------------------------------------: |
| [**47**](https://github.com/MarianaSouza/web-dev-path/issues/47) |

#### What is this change?
The change is replacing all the CSS files to SCSS files and referencing the related SCSS files in the components.

#### Were there any complications while making this change?
No

#### How did you verify this change?
Locally

#### When should this be merged?
After review and approval.

2021-08-19 04:38 UTC, MarianaSouza requested changes
This PR is almost there @ZahraB21 ! Great job!
When applying those fixes, please test the changes locally before committing, OK?

2021-08-19 04:38 UTC, MarianaSouza commented on styles/Home.module.scss
> +hr.divider {
Could you please apply the Sass nesting principle here too if possible, @ZahraB21 ?
hr {
  &.divider {
   // code
  }
 }

2021-08-19 04:38 UTC, MarianaSouza commented on styles/Layout.module.scss
> +.container {
Could you please fix the indentation on the 2 classes and media query on this file, @ZahraB21 ?
It seems you added 2 tab spaces instead of just 1.

2021-08-19 04:38 UTC, MarianaSouza commented on styles/_variables.scss
> +// Media Query Breakpoints
This is awesome, @ZahraB21! <3

2021-08-19 04:38 UTC, MarianaSouza commented on styles/Layout.module.scss
> +@media (min-width: 1024px) {
Since you created the variables file, could you please replace the 1024px for its respective variable here @ZahraB21 ?

2021-08-19 04:38 UTC, MarianaSouza commented on styles/Nav.module.scss
> +// .nav {
Could you please remove this code commented out?
As we're version controlling things, we don't need to keep them  :)

2021-08-19 04:38 UTC, MarianaSouza commented on styles/Nav.module.scss
> +    width: 80%;
Could you please fix the indentation on the 2all the classes and media query on this file, @ZahraB21 ?
It seems you added 2 tab spaces instead of just 1.

2021-08-19 04:38 UTC, MarianaSouza commented on styles/Nav.module.scss
> +@media (min-width: 768px) {
Since you created the variables file, could you please replace the 768px for its respective variable here @ZahraB21 ?

2021-08-31 18:06 UTC, ZahraB21 commented on styles/Nav.module.scss
> +@media (min-width: 768px) {
I have added the media query breakpoint variable.

2021-08-31 18:07 UTC, ZahraB21 commented on styles/Nav.module.scss
> +    width: 80%;
I have edited the tab indentation to 2 spaces. Before it was set to 4 spaces and that is why you thought I have 2 tab indentation.

2021-08-31 18:07 UTC, ZahraB21 commented on styles/Nav.module.scss
> +// .nav {
I have removed the comment.

2021-08-31 18:07 UTC, ZahraB21 commented on styles/Layout.module.scss
> +@media (min-width: 1024px) {
Replaced 1024 with media query breakpoint variable.

2021-08-31 18:08 UTC, ZahraB21 commented on styles/Layout.module.scss
> +.container {
I have fixed the indentation.

2021-08-31 18:08 UTC, ZahraB21 commented on styles/Home.module.scss
> +hr.divider {
I have edited the styling.

2021-09-04 23:42 UTC, MarianaSouza approved these changes
I've added some color variables, I've done some general styling normalization, and I think this is ready for merge @ZahraB21 !
Great work on this one! <3

2021-09-07 19:32 UTC, MarianaSouza approved these changes
Looks ready to shine, @ZahraB21 !

2021-09-07 19:33 UTC, merged