add image component
MarianaSouza/web-dev-path pull request #65
Opened 2021-12-20 01:25 UTC by panoramine

|                        Web Dev Path                      |
| :-----------------------------------------------------------: |
| [**64**](https://github.com/MarianaSouza/web-dev-path/issues/64) |

#### What is this change?
Substitution of the img element for the new [Image Component](https://nextjs.org/docs/basic-features/image-optimization) for better performance and automatic Image Optimization. This change was made for the logo (Navigation bar and Footer)  and social media icons on the Footer.
The Image Component mandatory properties:
- height
- width
- src

#### Were there any complications while making this change?
The social media icons lost their style after the change. Based on [research](https://github.com/vercel/next.js/discussions/22861) I made and with the assistance of fellow developer @rebecatschiedel I fixed the bug adding a new section tag to wrap the Image component and then styling the section instead of trying to style the Image directly. 
Although the issue was correctly fixed, we could not understand why we cannot use padding and margins while styling the Image component. 
It was also noticed that the use of the Image component created a new DOM structure inside the section tag like this:
`
<section>
    <div>
        <div>
            <img />
        </div>
        
        <img />   
    </div>
</section>    
`

This [situation](https://github.com/vercel/next.js/discussions/18820) was also noticed by other people.

#### How did you verify this change?
Locally on my branch feature/add-image-component.

#### When should this be merged?
After code review.

2021-12-20 01:49 UTC, MarianaSouza commented on components/Footer.js
> +              <section className={footerStyles.socialMedia}>
Instead of wrapping the new `<Image />` component into a new element with the same `className` of its parent, which seems a little repetitive, could you please try the second approach described[ in your research](https://github.com/vercel/next.js/discussions/22861), @panoramine , please?
That means you're just adding a new class to the <Image /> component itself and, then, styling it (add a margin-right between the images, if necessary).

![Screenshot 2021-12-19 173727](https://user-images.githubusercontent.com/20016897/146700514-525499d0-132c-497d-8c6e-ad7bdd821418.png)

2021-12-20 01:51 UTC, MarianaSouza requested changes
Please let me know if my comment above about the social media links makes sense, @panoramine :) Nice work so far!

2021-12-20 23:26 UTC, MarianaSouza approved these changes
I've done a commit to solve that styling issue without the section wrapper @panoramine  and @rebecatschiedel .
 If you agree and understand this code, please ask Rebeca to review it too, test it locally (or by using the Vercel PR preview), and then it's all yours to merge 🥳 
Way to go on your first PR! 🚀

2021-12-21 19:53 UTC, rebecatschiedel approved these changes
It was great to learn with you @panoramine and @MarianaSouza. It is so nice to see that we can achieve the same result in different ways and how to choose the best one for the project.

2021-12-23 21:22 UTC, merged